# Generated by Django 5.2.15 on 2026-06-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_alter_stock_id_watchlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='exchange',
            field=models.CharField(default='NSE', max_length=50),
        ),
    ]
