# Generated by Django 5.2.15 on 2026-06-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_stockprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=30)),
                ('status', models.CharField(choices=[('success', 'Success'), ('degraded', 'Degraded (possible drift)'), ('failed', 'Failed')], default='success', max_length=20)),
                ('rmse', models.FloatField(blank=True, null=True)),
                ('mae', models.FloatField(blank=True, null=True)),
                ('mape', models.FloatField(blank=True, null=True)),
                ('mse', models.FloatField(blank=True, null=True)),
                ('epochs_run', models.IntegerField(blank=True, null=True)),
                ('training_samples', models.IntegerField(blank=True, null=True)),
                ('test_samples', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ticker', '-created_at'], name='stocks_trai_ticker_f1dc83_idx')],
            },
        ),
    ]
